{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Componente2.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "authorship_tag": "ABX9TyOrNl01mFnMSjLMqsTpffCT",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Daniel4651111/TP-Open-Data/blob/main/Componente2.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "4PdHKxnQLDLZ"
      },
      "source": [
        "import pandas as pd\n",
        "from bs4 import BeautifulSoup\n",
        "import requests"
      ],
      "execution_count": 3,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "y6q2NpRqLHKy"
      },
      "source": [
        "no_pages = 1"
      ],
      "execution_count": 4,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "C6HZQt2JLJwj"
      },
      "source": [
        "def get_data(pageNo):  \n",
        "    headers = {\"User-Agent\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36\", \"Accept-Encoding\":\"gzip, deflate\", \"Accept\":\"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\", \"DNT\":\"1\",\"Connection\":\"close\", \"Upgrade-Insecure-Requests\":\"1\"}\n",
        "\n",
        "    r = requests.get('https://www.amazon.com/best-sellers-video-games/zgbs/videogames/ref=zg_bs_videogames_home_all?pf_rd_p=e01c95b7-d068-4132-b3df-99cf50bebb9b&pf_rd_s=center-4&pf_rd_t=2101&pf_rd_i=home&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=00SKV69X054MYBD93FBH&pf_rd_r=00SKV69X054MYBD93FBH&pf_rd_p=e01c95b7-d068-4132-b3df-99cf50bebb9b'+str(pageNo)+'?ie=UTF8&pg='+str(pageNo), headers=headers)#, proxies=proxies)\n",
        "    content = r.content\n",
        "    soup = BeautifulSoup(content)\n",
        "    \n",
        "\n",
        "    alls = []\n",
        "    for d in soup.findAll('div', attrs={'class':'a-section a-spacing-none aok-relative'}):\n",
        "        name = d.find('span', attrs={'class':'zg-text-center-align'})\n",
        "        n = name.find_all('img', alt=True)\n",
        "        brand = d.find('span', attrs={'class':'a-size-small a-color-base'})\n",
        "        rating = d.find('span', attrs={'class':'a-icon-alt'})\n",
        "        users_rated = d.find('a', attrs={'class':'a-size-small a-link-normal'})\n",
        "        price = d.find('span', attrs={'class':'p13n-sc-price'})\n",
        "\n",
        "        all1=[]\n",
        "\n",
        "        if name is not None:\n",
        "            all1.append(n[0]['alt'])\n",
        "        else:\n",
        "            all1.append(\"unknown-product\")\n",
        "\n",
        "        if brand is not None:\n",
        "            all1.append(brand.text)\n",
        "        elif brand is None:\n",
        "            brand = d.find('span', attrs={'class':'a-size-small a-color-base'})\n",
        "            if brand is not None:\n",
        "                all1.append(brand.text)\n",
        "            else:    \n",
        "                all1.append('0')\n",
        "\n",
        "        if rating is not None:\n",
        "            all1.append(rating.text)\n",
        "        else:\n",
        "            all1.append('-1')\n",
        "\n",
        "        if users_rated is not None:\n",
        "            all1.append(users_rated.text)\n",
        "        else:\n",
        "            all1.append('0')     \n",
        "\n",
        "        if price is not None:\n",
        "            all1.append(price.text)\n",
        "        else:\n",
        "            all1.append('0')\n",
        "        alls.append(all1)    \n",
        "    return alls\n"
      ],
      "execution_count": 5,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "g56T7shIOGFz"
      },
      "source": [
        "results = []\n",
        "for i in range(1, no_pages+1):\n",
        "    results.append(get_data(i))\n",
        "flatten = lambda l: [item for sublist in l for item in sublist]\n",
        "df = pd.DataFrame(flatten(results),columns=['Producto','Marca','Puntaje','Calificaciones', 'Precio'])\n",
        "df.to_csv('amazon_products.csv', index=False, encoding='utf-8')"
      ],
      "execution_count": 6,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "NYsWvu1KOMYt",
        "outputId": "54a6a196-5fd7-45af-8e37-b8d770573880"
      },
      "source": [
        "df "
      ],
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Producto</th>\n",
              "      <th>Marca</th>\n",
              "      <th>Puntaje</th>\n",
              "      <th>Calificaciones</th>\n",
              "      <th>Precio</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>$10 PlayStation Store Gift Card [Digital Code]</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>232,712</td>\n",
              "      <td>$10.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>PlayStation 5 Console</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>19,822</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>Xbox Series X</td>\n",
              "      <td>Xbox</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>7,979</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>$10 Xbox Gift Card [Digital Code]</td>\n",
              "      <td>Microsoft</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>117,508</td>\n",
              "      <td>$10.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>Xbox Series S</td>\n",
              "      <td>Microsoft</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>4,134</td>\n",
              "      <td>$349.95</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>Xbox Game Pass Ultimate: 3 Month Membership [D...</td>\n",
              "      <td>Microsoft</td>\n",
              "      <td>4.8 out of 5 stars</td>\n",
              "      <td>15,622</td>\n",
              "      <td>$29.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>Super Mario Odyssey - Nintendo Switch</td>\n",
              "      <td>Nintendo</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>23,922</td>\n",
              "      <td>$34.88</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>Razer Viper Mini Ultralight Gaming Mouse: Fast...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>15,280</td>\n",
              "      <td>$29.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>$10 Nintendo eShop Gift Card [Digital Code]</td>\n",
              "      <td>Nintendo</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>67,688</td>\n",
              "      <td>$5.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>Logitech G305 LIGHTSPEED Wireless Gaming Mouse...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>6,445</td>\n",
              "      <td>$49.95</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>10</th>\n",
              "      <td>Luigi's Mansion 3 - Nintendo Switch</td>\n",
              "      <td>Nintendo</td>\n",
              "      <td>4.8 out of 5 stars</td>\n",
              "      <td>22,058</td>\n",
              "      <td>$41.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>11</th>\n",
              "      <td>Legend of Zelda Link's Awakening - Nintendo Sw...</td>\n",
              "      <td>Nintendo</td>\n",
              "      <td>4.8 out of 5 stars</td>\n",
              "      <td>18,629</td>\n",
              "      <td>$43.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>12</th>\n",
              "      <td>Ghost of Tsushima - PlayStation 4</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>9,286</td>\n",
              "      <td>$39.88</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>13</th>\n",
              "      <td>Logitech G502 HERO High Performance Wired Gami...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>19,749</td>\n",
              "      <td>$37.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>14</th>\n",
              "      <td>PlayStation 5 Digital Edition</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>5,752</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>15</th>\n",
              "      <td>Shin Megami Tensei V: Steelbook Launch Edition...</td>\n",
              "      <td>SEGA</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>$59.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>16</th>\n",
              "      <td>Shin Megami Tensei V: Premium Edition - Ninten...</td>\n",
              "      <td>SEGA</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>17</th>\n",
              "      <td>Razer Kraken X Ultralight Gaming Headset: 7.1 ...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.4 out of 5 stars</td>\n",
              "      <td>15,941</td>\n",
              "      <td>$39.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>18</th>\n",
              "      <td>Roblox Gift Card - 800 Robux [Includes Exclusi...</td>\n",
              "      <td>Roblox</td>\n",
              "      <td>4.6 out of 5 stars</td>\n",
              "      <td>70,115</td>\n",
              "      <td>$10.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>19</th>\n",
              "      <td>Razer DeathAdder Essential Gaming Mouse: 6400 ...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>27,605</td>\n",
              "      <td>$26.44</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>20</th>\n",
              "      <td>RUNMUS Gaming Headset Xbox One Headset with 7....</td>\n",
              "      <td>0</td>\n",
              "      <td>4.4 out of 5 stars</td>\n",
              "      <td>85,777</td>\n",
              "      <td>$19.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>21</th>\n",
              "      <td>BENGOO G9000 Stereo Gaming Headset for PS4 PC ...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.4 out of 5 stars</td>\n",
              "      <td>66,761</td>\n",
              "      <td>$19.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>22</th>\n",
              "      <td>Razer DeathAdder Essential Gaming Mouse: 6400 ...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>27,605</td>\n",
              "      <td>$26.19</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>23</th>\n",
              "      <td>WD_BLACK 5TB P10 Game Drive, Portable External...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.8 out of 5 stars</td>\n",
              "      <td>19,456</td>\n",
              "      <td>$129.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>24</th>\n",
              "      <td>Razer DeathAdder V2 Gaming Mouse: 20K DPI Opti...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>27,605</td>\n",
              "      <td>$46.81</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>25</th>\n",
              "      <td>Razer Viper Ultimate Hyperspeed Lightest Wirel...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>15,280</td>\n",
              "      <td>$99.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>26</th>\n",
              "      <td>Sackboy: A Big Adventure – PlayStation 5</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.8 out of 5 stars</td>\n",
              "      <td>1,728</td>\n",
              "      <td>$39.88</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>27</th>\n",
              "      <td>Mario Golf: Super Rush - Nintendo Switch</td>\n",
              "      <td>Nintendo</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>$59.88</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>28</th>\n",
              "      <td>Razer Basilisk X HyperSpeed Wireless Gaming Mo...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.6 out of 5 stars</td>\n",
              "      <td>16,005</td>\n",
              "      <td>$49.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>29</th>\n",
              "      <td>Roblox Gift Card - 2000 Robux [Includes Exclus...</td>\n",
              "      <td>Roblox</td>\n",
              "      <td>4.6 out of 5 stars</td>\n",
              "      <td>70,115</td>\n",
              "      <td>$25.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>30</th>\n",
              "      <td>PlayStation DualSense Wireless Controller – Mi...</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.8 out of 5 stars</td>\n",
              "      <td>25,729</td>\n",
              "      <td>$69.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>31</th>\n",
              "      <td>Oculus Quest 2 — Advanced All-In-One Virtual R...</td>\n",
              "      <td>Oculus</td>\n",
              "      <td>4.8 out of 5 stars</td>\n",
              "      <td>49,089</td>\n",
              "      <td>$299.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>32</th>\n",
              "      <td>Returnal - PlayStation 5</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.4 out of 5 stars</td>\n",
              "      <td>571</td>\n",
              "      <td>$69.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>33</th>\n",
              "      <td>Danganronpa Decadence Collector's Edition - Ni...</td>\n",
              "      <td>Spike Chunsoft</td>\n",
              "      <td>-1</td>\n",
              "      <td>0</td>\n",
              "      <td>$99.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>34</th>\n",
              "      <td>Razer Cynosa Chroma Gaming Keyboard: Individua...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>11,368</td>\n",
              "      <td>$59.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>35</th>\n",
              "      <td>Razer Tartarus v2 Gaming Keypad: Mecha-Membran...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.4 out of 5 stars</td>\n",
              "      <td>7,905</td>\n",
              "      <td>$79.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>36</th>\n",
              "      <td>Assassin’s Creed Valhalla PlayStation 4 Standa...</td>\n",
              "      <td>Ubisoft</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>10,174</td>\n",
              "      <td>$40.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>37</th>\n",
              "      <td>Razer BlackShark V2 Pro Wireless Gaming Headse...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.5 out of 5 stars</td>\n",
              "      <td>10,613</td>\n",
              "      <td>$141.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>38</th>\n",
              "      <td>Pikmin 3 Deluxe - Nintendo Switch</td>\n",
              "      <td>Nintendo</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>5,721</td>\n",
              "      <td>$55.50</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>39</th>\n",
              "      <td>Logitech G703 Lightspeed Wireless Gaming Mouse...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>2,685</td>\n",
              "      <td>$59.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>40</th>\n",
              "      <td>Razer Kraken Tournament Edition THX 7.1 Surrou...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.5 out of 5 stars</td>\n",
              "      <td>6,250</td>\n",
              "      <td>$46.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>41</th>\n",
              "      <td>PlayStation Plus: 1 Month Membership [Digital ...</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>27,790</td>\n",
              "      <td>$9.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>42</th>\n",
              "      <td>Razer Kraken Ultimate RGB USB Gaming Headset: ...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.5 out of 5 stars</td>\n",
              "      <td>10,800</td>\n",
              "      <td>$101.86</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>43</th>\n",
              "      <td>NPET K10 Gaming Keyboard USB Wired Floating Ke...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.6 out of 5 stars</td>\n",
              "      <td>13,894</td>\n",
              "      <td>$21.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>44</th>\n",
              "      <td>VALORANT $10 Gift Card - PC [Online Game Code]</td>\n",
              "      <td>Riot Games</td>\n",
              "      <td>4.6 out of 5 stars</td>\n",
              "      <td>3,752</td>\n",
              "      <td>$10.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>45</th>\n",
              "      <td>PlayStation DualSense Wireless Controller – Co...</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.8 out of 5 stars</td>\n",
              "      <td>25,729</td>\n",
              "      <td>$74.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>46</th>\n",
              "      <td>HyperX Cloud Alpha S - PC Gaming Headset, 7.1 ...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.6 out of 5 stars</td>\n",
              "      <td>13,284</td>\n",
              "      <td>$128.60</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>47</th>\n",
              "      <td>Logitech G432 Wired Gaming Headset, 7.1 Surrou...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.4 out of 5 stars</td>\n",
              "      <td>4,116</td>\n",
              "      <td>$39.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>48</th>\n",
              "      <td>SteelSeries Arctis 5 - RGB Illuminated Gaming ...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.5 out of 5 stars</td>\n",
              "      <td>31,039</td>\n",
              "      <td>$66.49</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>49</th>\n",
              "      <td>Super Mario 3D World + Bowser's Fury - Nintend...</td>\n",
              "      <td>Nintendo</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>16,193</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "                                             Producto  ...   Precio\n",
              "0      $10 PlayStation Store Gift Card [Digital Code]  ...   $10.00\n",
              "1                               PlayStation 5 Console  ...        0\n",
              "2                                       Xbox Series X  ...        0\n",
              "3                   $10 Xbox Gift Card [Digital Code]  ...   $10.00\n",
              "4                                       Xbox Series S  ...  $349.95\n",
              "5   Xbox Game Pass Ultimate: 3 Month Membership [D...  ...   $29.99\n",
              "6               Super Mario Odyssey - Nintendo Switch  ...   $34.88\n",
              "7   Razer Viper Mini Ultralight Gaming Mouse: Fast...  ...   $29.99\n",
              "8         $10 Nintendo eShop Gift Card [Digital Code]  ...    $5.00\n",
              "9   Logitech G305 LIGHTSPEED Wireless Gaming Mouse...  ...   $49.95\n",
              "10                Luigi's Mansion 3 - Nintendo Switch  ...   $41.99\n",
              "11  Legend of Zelda Link's Awakening - Nintendo Sw...  ...   $43.99\n",
              "12                  Ghost of Tsushima - PlayStation 4  ...   $39.88\n",
              "13  Logitech G502 HERO High Performance Wired Gami...  ...   $37.99\n",
              "14                      PlayStation 5 Digital Edition  ...        0\n",
              "15  Shin Megami Tensei V: Steelbook Launch Edition...  ...   $59.99\n",
              "16  Shin Megami Tensei V: Premium Edition - Ninten...  ...        0\n",
              "17  Razer Kraken X Ultralight Gaming Headset: 7.1 ...  ...   $39.99\n",
              "18  Roblox Gift Card - 800 Robux [Includes Exclusi...  ...   $10.00\n",
              "19  Razer DeathAdder Essential Gaming Mouse: 6400 ...  ...   $26.44\n",
              "20  RUNMUS Gaming Headset Xbox One Headset with 7....  ...   $19.99\n",
              "21  BENGOO G9000 Stereo Gaming Headset for PS4 PC ...  ...   $19.99\n",
              "22  Razer DeathAdder Essential Gaming Mouse: 6400 ...  ...   $26.19\n",
              "23  WD_BLACK 5TB P10 Game Drive, Portable External...  ...  $129.00\n",
              "24  Razer DeathAdder V2 Gaming Mouse: 20K DPI Opti...  ...   $46.81\n",
              "25  Razer Viper Ultimate Hyperspeed Lightest Wirel...  ...   $99.99\n",
              "26           Sackboy: A Big Adventure – PlayStation 5  ...   $39.88\n",
              "27           Mario Golf: Super Rush - Nintendo Switch  ...   $59.88\n",
              "28  Razer Basilisk X HyperSpeed Wireless Gaming Mo...  ...   $49.99\n",
              "29  Roblox Gift Card - 2000 Robux [Includes Exclus...  ...   $25.00\n",
              "30  PlayStation DualSense Wireless Controller – Mi...  ...   $69.00\n",
              "31  Oculus Quest 2 — Advanced All-In-One Virtual R...  ...  $299.00\n",
              "32                           Returnal - PlayStation 5  ...   $69.00\n",
              "33  Danganronpa Decadence Collector's Edition - Ni...  ...   $99.99\n",
              "34  Razer Cynosa Chroma Gaming Keyboard: Individua...  ...   $59.99\n",
              "35  Razer Tartarus v2 Gaming Keypad: Mecha-Membran...  ...   $79.99\n",
              "36  Assassin’s Creed Valhalla PlayStation 4 Standa...  ...   $40.00\n",
              "37  Razer BlackShark V2 Pro Wireless Gaming Headse...  ...  $141.99\n",
              "38                  Pikmin 3 Deluxe - Nintendo Switch  ...   $55.50\n",
              "39  Logitech G703 Lightspeed Wireless Gaming Mouse...  ...   $59.99\n",
              "40  Razer Kraken Tournament Edition THX 7.1 Surrou...  ...   $46.99\n",
              "41  PlayStation Plus: 1 Month Membership [Digital ...  ...    $9.99\n",
              "42  Razer Kraken Ultimate RGB USB Gaming Headset: ...  ...  $101.86\n",
              "43  NPET K10 Gaming Keyboard USB Wired Floating Ke...  ...   $21.99\n",
              "44     VALORANT $10 Gift Card - PC [Online Game Code]  ...   $10.00\n",
              "45  PlayStation DualSense Wireless Controller – Co...  ...   $74.99\n",
              "46  HyperX Cloud Alpha S - PC Gaming Headset, 7.1 ...  ...  $128.60\n",
              "47  Logitech G432 Wired Gaming Headset, 7.1 Surrou...  ...   $39.99\n",
              "48  SteelSeries Arctis 5 - RGB Illuminated Gaming ...  ...   $66.49\n",
              "49  Super Mario 3D World + Bowser's Fury - Nintend...  ...        0\n",
              "\n",
              "[50 rows x 5 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 7
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "ViyVEb2-RRxz"
      },
      "source": [
        "df = pd.read_csv(\"amazon_products.csv\")"
      ],
      "execution_count": 8,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "I-8qLZF8RUvp",
        "outputId": "968c231b-eac4-4126-cdc1-147efdd1a892"
      },
      "source": [
        "df.shape"
      ],
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "(50, 5)"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 9
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 359
        },
        "id": "j3DCk6EqcSgz",
        "outputId": "4e56c27e-2134-49c1-a65f-9b3ebc9a4190"
      },
      "source": [
        "df.head(10)"
      ],
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Producto</th>\n",
              "      <th>Marca</th>\n",
              "      <th>Puntaje</th>\n",
              "      <th>Calificaciones</th>\n",
              "      <th>Precio</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>$10 PlayStation Store Gift Card [Digital Code]</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>232,712</td>\n",
              "      <td>$10.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>PlayStation 5 Console</td>\n",
              "      <td>PlayStation</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>19,822</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>Xbox Series X</td>\n",
              "      <td>Xbox</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>7,979</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>$10 Xbox Gift Card [Digital Code]</td>\n",
              "      <td>Microsoft</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>117,508</td>\n",
              "      <td>$10.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>Xbox Series S</td>\n",
              "      <td>Microsoft</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>4,134</td>\n",
              "      <td>$349.95</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>Xbox Game Pass Ultimate: 3 Month Membership [D...</td>\n",
              "      <td>Microsoft</td>\n",
              "      <td>4.8 out of 5 stars</td>\n",
              "      <td>15,622</td>\n",
              "      <td>$29.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>Super Mario Odyssey - Nintendo Switch</td>\n",
              "      <td>Nintendo</td>\n",
              "      <td>4.9 out of 5 stars</td>\n",
              "      <td>23,922</td>\n",
              "      <td>$34.88</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>Razer Viper Mini Ultralight Gaming Mouse: Fast...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>15,280</td>\n",
              "      <td>$29.99</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>$10 Nintendo eShop Gift Card [Digital Code]</td>\n",
              "      <td>Nintendo</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>67,688</td>\n",
              "      <td>$5.00</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>Logitech G305 LIGHTSPEED Wireless Gaming Mouse...</td>\n",
              "      <td>0</td>\n",
              "      <td>4.7 out of 5 stars</td>\n",
              "      <td>6,445</td>\n",
              "      <td>$49.95</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "                                            Producto  ...   Precio\n",
              "0     $10 PlayStation Store Gift Card [Digital Code]  ...   $10.00\n",
              "1                              PlayStation 5 Console  ...        0\n",
              "2                                      Xbox Series X  ...        0\n",
              "3                  $10 Xbox Gift Card [Digital Code]  ...   $10.00\n",
              "4                                      Xbox Series S  ...  $349.95\n",
              "5  Xbox Game Pass Ultimate: 3 Month Membership [D...  ...   $29.99\n",
              "6              Super Mario Odyssey - Nintendo Switch  ...   $34.88\n",
              "7  Razer Viper Mini Ultralight Gaming Mouse: Fast...  ...   $29.99\n",
              "8        $10 Nintendo eShop Gift Card [Digital Code]  ...    $5.00\n",
              "9  Logitech G305 LIGHTSPEED Wireless Gaming Mouse...  ...   $49.95\n",
              "\n",
              "[10 rows x 5 columns]"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 10
        }
      ]
    }
  ]
}